permalink: pretty

title: Axinite
tagline: Prototype Blog
flair: Uncomplicated CSS

baseurl: https://axnt.github.io/jekyll
twitter: getaxinite
paginate: 2
paginate_path: "/page/:num/"

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Axinite
  url: https://twitter.com/getaxinite
  email: citrusui@users.noreply.github.com

version: 0.0.9

repo: https://github.com/axnt/jekyll

theme: axinite

exclude:
  - Gemfile
  - Gemfile.lock

gems:
  - jekyll-feed
  - jekyll-paginate
